### ISSUE TITLE
date wrong

### ISSUE THREAD

**Issue by chreman** [DLiNa/project#5]
in ANONYME_RESURRECTIONJENINLANDORE.xml:
`<date type="print" when="v.1500">v.1500</date>`

**Comment by chreman** [comment]
most likely causes this, when plotting superposter:

```
Traceback (most recent call last):
  File "dramavis.py", line 619, in <module>
    main(args)
  File "dramavis.py", line 607, in main
    plot_superposter(inputfolder, outputfolder)
  File "dramavis.py", line 479, in plot_superposter
    sorted_by_date = sorted(id2date, key=id2date.__getitem__)
TypeError: unorderable types: NoneType() < int()
```

**Comment by lehkost** [comment]
since "v." means "vers" we could easily just match the four-digit year number, what do you think? – after all, the years will just come into play when we plot chronologically and metadata stays untouched.
